### PR TITLE
The function to compute the force of a body was done

### PR DESCRIPTION
**Pull request by Eyenike40**
The program compute the force of a body. Also, a get object mass input from the user was a function done seperately.

### CODE REVIEW

**Review by Eyenike40 — COMMENTED** [review]
Write a test for the program

**Comment by Eyenike-James** [comment]
A test function for the force program has been done

**Review by Eyenike40 — COMMENTED** [review]
Code ok, has has been merged to the master

**Comment by Eyenike-James** [comment]
Thanks

**Pull request merged**
